name: node.js

on: [pull_request]

jobs:
  yarn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install apt dependencies
        run: sudo apt install libdbus-1-dev libglib2.0-dev
      - run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
